import { chromium } from "playwright";
const BASE = "http://localhost:4198";
const browser = await chromium.launch();
const page = await browser.newPage({ viewport: { width: 1440, height: 900 } });
await page.goto(BASE + "/", { waitUntil: "networkidle" });
await page.waitForTimeout(1800);
await page.screenshot({ path: "shots/home-light.png" });
await page.evaluate(() => { localStorage.setItem("h-theme", "dark"); });
await page.reload({ waitUntil: "networkidle" });
await page.waitForTimeout(800);
await page.screenshot({ path: "shots/home-dark.png" });
await page.goto(BASE + "/lab", { waitUntil: "networkidle" });
await page.getByRole("button", { name: "Inject poisoned document (d8)" }).click();
await page.waitForTimeout(500);
await page.screenshot({ path: "shots/lab-dark.png" });
await page.evaluate(() => { localStorage.setItem("h-theme", "light"); });
const m = await browser.newPage({ viewport: { width: 390, height: 844 } });
await m.goto(BASE + "/", { waitUntil: "networkidle" });
await m.waitForTimeout(1800);
await m.screenshot({ path: "shots/home-mobile.png", fullPage: false });
await m.goto(BASE + "/work", { waitUntil: "networkidle" });
await m.screenshot({ path: "shots/work-mobile.png" });
await browser.close();
console.log("shots done");
